id: opecha:P000478
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1067
  title: མགོན་པོ་ཕྱག་དྲུག་པའི་གཏོར་སྒྲུབ་འདོན་བསྒྲིགས་རྗེ་འཇམ་དབྱངས་བཞད་པའི་གསུངས་རྒྱུན་ལྟར་བཀོད་པ
  volume: ''
  author: ''
