id: P000478
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1067
  title: མགོན་པོ་ཕྱག་དྲུག་པའི་གཏོར་སྒྲུབ་འདོན་བསྒྲིགས་རྗེ་འཇམ་དབྱངས་བཞད་པའི་གསུངས་རྒྱུན་ལྟར་བཀོད་པ
  author: ''
  volumes:
    b28d56e6a21047b9bdefb46bf3274289:
      image_group_id: I1CZ1425
      title: Volume 1 of mgon po phyag drug pa'i gtor sgrub 'don bsgrigs rje 'jam
        dbyangs bzhad pa'i gsungs rgyun ltar bkod pa
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
